language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="dns-lwt-unix:. mirage-dns:. dns:. dns-lwt:. dns-async:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="dns-lwt-unix" OCAML_VERSION="4.03.0"
  - PACKAGE="dns-lwt-unix" OCAML_VERSION="4.04.2"
  - PACKAGE="dns-lwt-unix" OCAML_VERSION="4.05.0"
  - PACKAGE="dns-lwt-unix" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-dns" OCAML_VERSION="4.03.0"
  - PACKAGE="mirage-dns" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-dns" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-dns" OCAML_VERSION="4.06.0"
  - PACKAGE="dns" OCAML_VERSION="4.03.0"
  - PACKAGE="dns" OCAML_VERSION="4.04.2"
  - PACKAGE="dns" OCAML_VERSION="4.05.0"
  - PACKAGE="dns" OCAML_VERSION="4.06.0"
  - PACKAGE="dns-lwt" OCAML_VERSION="4.03.0"
  - PACKAGE="dns-lwt" OCAML_VERSION="4.04.2"
  - PACKAGE="dns-lwt" OCAML_VERSION="4.05.0"
  - PACKAGE="dns-lwt" OCAML_VERSION="4.06.0"
  - PACKAGE="dns-async" OCAML_VERSION="4.03.0"
  - PACKAGE="dns-async" OCAML_VERSION="4.04.2"
  - PACKAGE="dns-async" OCAML_VERSION="4.05.0"
  - PACKAGE="dns-async" OCAML_VERSION="4.06.0"
